# .github/workflows/release.yml
name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.0.0" # 你可以根据需要更改Flutter版本

      - name: Install dependencies
        run: flutter pub get

      - name: Build Windows
        run: flutter build windows --release

      - name: Upload Windows Build
        uses: actions/upload-artifact@v2
        with:
          name: windows-build
          path: build/windows/runner/Release

  publish:
    needs: build
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Download Windows Build
        uses: actions/download-artifact@v2
        with:
          name: windows-build
          path: windows-build

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            windows-build/*.exe
            windows-build/*.dll
            windows-build/*.pdb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
